This is just a quick intro to Numpy. For this lecture go to the following links and take a quick glance at what numpy is capable of. Remember, you should have already installed numpy already using pip install numpy or conda install numpy. 

Here is the link the official course notebooks:

http://nbviewer.jupyter.org/github/jmportilla/Udemy-notes/tree/master/

Alternative link:

https://github.com/jmportilla/Udemy-notes/tree/master/

And here are some extra resources for Numpy.

Reference for all of numpy:

http://docs.scipy.org/doc/numpy/reference/

Supplemental materials in case your interested in more than just the video lectures:

http://cs231n.github.io/python-numpy-tutorial/

Great! Now let's go ahead and get started with learning numpy with the next video lectures!

In [3]:
# Creating Numpy arrays
import numpy as np

In [4]:
# Converting from a list
#Lets start with a list

my_list1 = [1,2,3,4]

In [5]:
my_array1 = np.array(my_list1)
my_array1

array([1, 2, 3, 4])

In [6]:
# Make another list
my_list2 = [11,22,33,44]
#Make a list of lists
my_lists = [my_list1,my_list2]

In [7]:
#Make multi-dimensional array/matrix
my_array2 = np.array(my_lists)

#Show array
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [9]:
#Lets get the size of the array
my_array2.shape

(2, 4)

In [10]:
#Find out the data tyoe of the array
my_array2.dtype

dtype('int32')

In [11]:
#Making special case arrays

#Zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [32]:
# another way of writing
# refer to https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty.html more details
np.empty((2,2)) # not always zeros

array([[7.04684547e-312, 2.29178686e-312],
       [3.44898501e-307, 4.00536722e-307]])

In [21]:
#Ones
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
#Identity array
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
# Using a range

np.arange(5)

array([0, 1, 2, 3, 4])

In [36]:
np.arange(5,50,2) # start number follow by end number and how many steps increment

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

summary
1) pass list np.array
2) check shape and type
3) special arrays empty, zero, one and eye and arange