In [1]:
import numpy as np


In [2]:
#exact amount
5/2 

2.5

In [3]:
#return integar
5//2

2

In [4]:
#return reminder
5%2

1

In [10]:
# Create array
arr1 = np.array([[1,2,3,4],[8,9,10,11]])
x = arr1.shape
print ("My array is:", x)
arr1

My array is: (2, 4)


array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [11]:
#Multiplying Arrays multiple the same spot
arr1 * arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [12]:
#Subtraction
arr1-arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
#Arithmetic operations with scalars on array
1 / arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [15]:
#Exponential operation to the power of
arr1 ** 3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]], dtype=int32)

In [ ]:
# scalers of operations