In [1]:
import numpy as np

# Universal functions perform operations on all elements in an array

In [2]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#basic function to that can be apply to the array 
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
# Binary Functions require two arrays

#Random array (normal dist)
A = np.random.randn(10)

A

array([ 0.16226096,  1.09846498,  1.63733819,  1.61691922, -0.92521378,
       -0.385804  ,  0.35320912, -2.15715611, -0.69725361,  0.56605575])

In [7]:
B = np.random.randn(10)
B

array([-1.38578817, -1.08655556,  0.30199913,  1.40426005, -1.17337297,
       -1.9893723 , -1.04508227, -1.93987641,  0.60607945, -0.22267838])

In [8]:
#Addition
np.add(A,B)

array([-1.22352721,  0.01190941,  1.93933731,  3.02117927, -2.09858675,
       -2.37517629, -0.69187315, -4.09703252, -0.09117416,  0.34337737])

In [9]:
#Finding max or min between two arrays
np.maximum(A,B)

array([ 0.16226096,  1.09846498,  1.63733819,  1.61691922, -0.92521378,
       -0.385804  ,  0.35320912, -1.93987641,  0.60607945,  0.56605575])

In [11]:
#For full and extensive list of all universal functions
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True