In [20]:
import numpy as np

In [21]:
arr =np.arange(5)

In [22]:
arr

array([0, 1, 2, 3, 4])

In [23]:
#Saving array on disk in binary format (file extension .npy)
np.save('myarray',arr)

In [24]:
#Change arr
arr = np.arange(10)

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
#Lets see the original saved copy
np.load('myarray.npy') # must call the extension

array([0, 1, 2, 3, 4])

In [27]:
arr1 = np.load('myarray.npy')
arr1

array([0, 1, 2, 3, 4])

In [28]:
arr2 = arr

In [29]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
#Saving multiple arrays into a zip file
np.savez('ziparray.npz',x=arr1,y=arr2)

In [31]:
archive_array = np.load('ziparray.npz')

In [32]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [33]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
np.savetxt('mytextarray.txt',arr,delimiter=',')

In [36]:
arr = np.loadtxt('mytextarray.txt',delimiter=',')
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

#recap
load and save arrays
load and save as txt files
files are save at the same folder

SyntaxError: invalid syntax (<ipython-input-38-ac97e31f7118>, line 2)